#Developed by: _ItsAndrew_
#This file is for configuring the main parts of the plugin

#Echoes Of Gold PAPI Placeholders:
#     %eog_balance% -> Display the player's balance
#     %eog_end_date% -> Display the end date of the tournament.

chat-prefix: "&f&l[&6&lEOG&f&l]" #This is the prefix that shows up in the chat

toggle-fireworks-effect: true #Toggle the fireworks effect when a player clicks on a treasure
fw-main-color: "#5d30bf"  #Use HEX COLORS
fw-second-color: "#23bad9" #Use HEX COLORS

#Configure the location where players are teleported when the event begins
teleport-location-x: ""
teleport-location-y: ""
teleport-location-z: ""

#Configure the title/subtitle when the event begins
title: "" #Use "&" for style
subtitle: "" #Use "&" for style

#Configure the start-book. It is the book that appears right after you enable the event.
start-book:
  toggle: true #true(yes) / #false(no)
  delay: 2 #Delay after the event starts (in seconds)
  author: "&cServer Staffs"
  title: "&6&lECHOES OF GOLD - INFO"
  pages: #Use '\n' to go on a new line in a page
    - "&5Welcome, adventurer!\n\n&6The night of terror begins...\n3 cursed chests await for you in the Overworld.\n\n&cFind them before they find you."
    - "&7Each chest holds &eancient treasures&7.\nBut beware...\nSome are guarded by monsters.\n\n&4Good luck!"

#Configure the Economy part of the plugin.
economy:
  toggle-using-economy: true

  #This pops a little message above the XP bar to the player when they find a treasure.
  #Use '%coins_amount%' to display how many coins the player got. Use '&' for styles
  action-bar-message: "&6You got %coins_amount% coins!"

  #Configure the internal economy. Note that you will need to restart the server if you make changes here when it is online.
  internal-economy:
    toggle: true #Setting this to FALSE will use the Vault + An economy plugin instead of the internal one. Shop will also be disabled.
    database-system:
      type: sqlite #Use 'sqlite' if you run only one server. Use 'mysql' if you have multiple servers.
      file-name: "database.db" #This is only used if you use 'sqlite'!

      #These are the settings for the MySQL database. If you don't use MySQL, you can ignore this.
      host: ""
      port: ""
      database: ""
      username: ""
      password: ""

  #Configure the shop GUI. If the internal economy is disabled, the shop won't work.
  shop-gui:
    rows: 6 #Value must be between 1 and 6. Each row has 9 slots.
    shop-title: "Event Shop" #This will appear to the players.
    remove-item-title: "Click To Remove" #This will appear if you want to remove an item from the shop.
    displaying-the-price: "&aPrice: &f%item_price%" #Use '%item_price%' for displaying the price of the item

    #Configure some chat messages
    not-enough-money-message: "&cYou don't have enough money to buy this!"
    no-inventory-space-message: "&cYou don't have enough inventory space!"
    successful-purchase-message: "&aYou bought &l%item_name% &afor &l%item_price% &acoins!" #Use '%item_name%' and '%item_price%' for displaying the name and price of the item.

    #Configure an exit item
    exit-item:
      material: red_concrete #The material of the item
      slot: 49
      display-name: "&c&lEXIT" #Use '&' for styles

    #Configure a 'no items' item
    no-items-item:
      material: barrier
      slot: 22
      display-name: "&eThere are no items set yet!"

    #Configure a 'player head' item where players can see their info (e.g. balance)
    player-head-item:
      toggle: true #If you want this or not
      display-name: "&e%player_name%" #Use '%player_name%' to display their ign
      lore:
        - " "
        - "&7Your Balance: &f%eog_balance%" #Use '%eog_balance%' to display their balance
      slot: 4

    #Configure some decoration (on top of the gui)
    decoration:
      #If you set this to 'false', the shop items will appear from the top of the GUI
      toggle: true
      material: black_stained_glass_pane #Material for the deco
      display-name: " " #Leave like this for no display name

    #Configuration for the shop items. (Use /eog shop addItem <price>/removeItem)
    items: ""

  #Configure a shop item, which players can interact with and open the shop.
  #Note that if the internal economy is disabled, this feature will be disabled as well.
  shop-item:
    toggle: true #Whether you want this feature or not

    #This item will only be available in 'lobby' worlds, so here enter the name of the 'lobby worlds'
    #The name of the world is the name of the world folder.
    #If you make any changes here, you need to restart the server!
    lobby-worlds:
      -

    hotbar-slot: 2 #The slots start from 0 -> 8
    material: emerald
    display-name: "&6&lEVENT SHOP" #Use '&' for styles
    lore:
      - " "
      - "&7Right click to access the shop"

#Configure general messages. Use "&" for style
treasure-already-found: "&cYou have &lalready found &cthis treasure!" #Use & for style
treasure-found: "&aYou have found a &ltreasure&a!"
player-found-all-treasures: "&6&lGG! &6You have found all the treasures!"
no-inventory-space-message: "&cYou don't have enough inventory space!"


#Configure the /eog disable titles. These will appear when you run /eog disable to disable the event.
disable-titles:
  toggle: true #If you want to use these titles or not
  main-title: "&c&lEVENT CANCELLED!"
  subtitle: "&f&lBe on the lookout for news about this."

#Configure the messages/titles/subtitles during the event. Use '&' for style.
toggle-event-messages: true
event-three-quarters-time: #Configure the messages for the 3/4 of the time left
  toggle: true
  chat-message-lines: #Use %three_quarters_time% to display 3/4 of the time left
    - "&a&lTIME LEFT: &a%three_quarters_time%"
    - "&aHurry!"
  toggle-title-subtitle: true
  title:
    message: "&f&lHURRY!"
  subtitle:
    message: "&aOnly &l%three_quarters_time% seconds &aleft!"

event-half-time: #Configure the messages for the 1/2 of the time left
  toggle: true
  chat-message-lines: #Use %half_time% to display 1/2 of the time left
    - "&a&lTIME LEFT: &a%half_time%"
    - "&aHurry!"
  toggle-title-subtitle: true
  title:
    message: "&f&lHURRY!"
  subtitle: #Same is this
    message: "&aOnly &l%half_time% &aseconds left!"

event-one-quarter-time: #Configure the messages for the 1/4 of the time left
  toggle: true
  chat-message-lines: #Use %one_quarter_time% to display 1/4 of the time left
    - "&a&lTIME LEFT: &a%one_quarter_time% seconds!"
  toggle-title-subtitle: true
  title:
    message: "&f&lHURRY!"
  subtitle:
    message: "&aOnly &a&l%one_quarter_time% &aseconds left!"

event-final-time: #This is the time when the event ends
  finish-event-message:
    toggle: true
    #PLACEHOLDERS:
    # - %topN_name% -> The top N player's IGN (N = {1,2,3})
    # - %topN_count% -> The top N player's treasures found (N = {1,2,3})
    message-lines:
      - "      &c&lEVENT FINISHED"
      - ""
      - ""
      - "  &e1) &l%top1_name% &e- &l%top1_count% &etreasures"
      - "  &72) &l%top2_name% &7- &l%top2_count% &7treasures"
      - "  &63) &l%top3_name% &6- &l%top3_count% &6treasures"
      - ""
      - ""
      - " &d&lTHANK YOU FOR PARTICIPATING!"
  final-countdown:
    seconds-to-start: 10 #Set the seconds from when the countdown will begin
    title: "&d&l%cooldown_time%" #Use %cooldown_time% to display the timer
    subtitle: ""
  #This is the title/subtitle that appears when the event finishes
  finish-event-title: "&e&lTREASURE HUNT IS FINISHED!"
  finish-event-subtitle: "&aCongrats %player_name% for your progress." #Use %player_name% to display the player's name

#Configure the Hints GUI settings
hints-gui:
  toggle-hints: false #If you want to use hints or not. You will have to restart the server for changes to take effect.

  gui-rows: 6 #Value must be between 1 and 6. Each row has 9 slots => 9 slots-minimum, 54 slots-maximum
  gui-title: "Hints"

  #Configure the lore for an unlocked hint
  unlocked-hint-lore:
    - "&a✔ &lUnlocked"
    - " "
    - "&7Click to open the hint"

  #Configure the lore for a locked hint
  locked-hint-lore:
    - "&e🔒 &lLocked"
    - " "
    - "&cYou already found this treasure!"

  #Configure a 'Hints Item' during the event which players can interact with to open the gui.
  #It only appears when there are hints configured!
  hints-item:
    toggle: true #Whether you want this item or not
    hotbar-slot: 8 #The slot in which the player will get this item. Values are from 0 to 8!
    material: enchanted_book
    display-name: "&6&lHINTS" #The display name of the item
    lore: #The lore of the item. Leave blank for none
      - " "
      - "&7Click to view hints for the treasures!"

  toggle-decorations: true #Whether you want decorations or not
  decoration-material: black_stained_glass_pane

  #Configure the info-item. Handy for displaying some tips/etc.
  info-item:
    toggle: true #Whether you want this item in your GUI or not
    slot: 4 #The slot for the item
    display-name: "&fChoose a hint to open" #Use '&' for styles
    material: oak_sign #The material

  #Configure the exit-button
  exit-button:
    toggle: true #Whether you want this button or not
    slot: 49
    material: red_concrete #The item that the button will have
    display-name: "&c&lEXIT"

#Configure every sound for the plugin. For checking AND hearing every sound, run /playsound in minecraft, then write what is after "minecraft:"
#As for the volume and pitch, the default value is 1
start-event-sound: "entity.wither.spawn"
ses-volume: 1
ses-pitch: 1

countdown-sound: "block.note_block.hat"
cs-volume: 1
cs-pitch: 1

event-finish-sound: "entity.ender_dragon.death"
efs-volume: 1
efs-pitch: 1

event-three-quarter-time-sound: "block.note_block.hat"
etqts-volume: 1
etqts-pitch: 1

event-half-time-sound: "block.note_block.hat"
ehts-volume: 1
ehts-pitch: 1

event-one-quarter-time-sound: "block.note_block.hat"
eoqts-volume: 1
eoqts-pitch: 1

player-clicked-on-unknown-hint-sound: "entity.enderman.teleport"
pcouhs-volume: 1
pcouhs-pitch: 1

no-hints-item-sound: "entity.villager.no"
nhis-volume: 1
nhis-pitch: 0.8

treasure-found-sound: "entity.enderman.teleport"
tfs-volume: 1
tfs-pitch: 1

treasure-has-no-items-sound: "entity.villager.no"
thni-volume: 1
thni-pitch: 1

no-inventory-space-sound: "entity.enderman.teleport"
niss-volume: 1
niss-pitch: 1

treasure-click-sound: "entity.experience_orb.pickup"
tcs-volume: 1
tcs-pitch: 1.2

hint-open-sound: "item.book.page_turn"
hos-volume: 1
hos-pitch: 1

event-disabled-sound: "entity.ender_dragon.death"
eds-volume: 1
eds-pitch: 1

#Configure the treasures custom head
#For this you need to go to "https://minecraft-heads.com/", search for a desired custom head, then copy and paste the VALUE
custom-head: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGJmNzJiNmZjZGM4Zjk1ZGYyOGYwNmY0MTUyZWE4YzliZTM4ZGEyODViMmNlZTA0ZTViZWQyMTUzYjM4OWQ5YiJ9fX0="

#Configure the particles. Try to play with all the offset/extra values :)
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html <- go here for all available particles
treasures-particle:
  toggle: true #Whether you want these particles or not
  particle: PORTAL
  count: 40
  offsetX: 0.4
  offsetY: 0.5
  offsetZ: 0.4
  extra: 0 #This is extra data for the particle, usually speed.

treasure-found-particle:
  toggle: true #Whether you want this particle or not
  particle: CRIT
  count: 30
  offsetX: 0.2
  offsetY: 0.3
  offsetZ: 0.2
  extra: 0 #Again, extra data for the particle, usually speed.

#This is the duration of the whole event.
event-duration: "1m" #d -> days; h -> hours; m -> minutes; s -> seconds

#This is the pattern for displaying the End Date of the tournament.
#d -> day ; M -> Month (Letter) ; y -> year ; H -> hour ; m -> minute ; s -> second
end-date-placeholder-format: "dd MMM yyyy HH:mm:ss"

#BOSS BAR
boss-bar: true #true(yes)/false(no)
bar-title: "&6&Treasure Hunt Active!"
bar-title-ended: "&c&lTreasure Hunt Ended! Thanks for your participation. "
bar-title-time-left: "&5&lTime left: %time_left%. &5TIP: Use &l/hints" #Use '%time_left%' for displaying the time.
stop-boss-bar-interval: 10 #Stop the boss bar after <interval> seconds when event ends

#SCOREBOARD
#AVAILABLE PLACEHOLDERS:
#%player_name% -> Display's the player's IGN
#%topN_name% -> The top N player's IGN (N = {1,2,3})
#%topN_count% -> The top N player's treasures found (N = {1,2,3})
#%player_treasures% -> Displays the player's number of found treasures
#%max_treasures% -> Displays the max treasures of the event (configured in treasures.yml)
#%coins_gathered% -> Displays the coins the player found
scoreboard: true #true(yes)/false(no)
scoreboard-interval: 1 #Updates the scoreboard in this interval of time (seconds)
scoreboard-title: "&f💎 &6&lTREASURE HUNT &f💎"
scoreboard-lines:
  - "&aPlayer: &f%player_name%"
  - "&7----------------"
  - "&f&l[&a🏆&f&l] &1&lTOP 3 PLAYERS:"
  - "&6&l1. &6%top1_name% &7- &f%top1_count%"
  - "&e&l2. &e%top2_name% &7- &f%top2_count%"
  - "&c&l3. &c%top3_name% &7- &f%top3_count%"
  - "&7---------------"
  - "&f&l[&a🎁&f&l] &aTreasures Found: &f%player_treasures%/%max_treasures%"
  - "&f&l[&a🪙&f&l] &aCoins Gathered: &f%coins_gathered%" #This line will only appear if the Economy is toggled and working!

#Configure the help command message
#Use '&' for color codes
help-message:
  lines:
    - "&c&l--------------------------------------------------------"
    - "&f&l====[&6&lECHOES OF GOLD HELP&f&l]===="
    - " "
    - "&l/eog enable &r-> enables the event"
    - "&l/eog disable &r-> disables the event"
    - "&l/eog reload &r-> reloads the config of the plugin"
    - "&l/eog event ... &r-> manage main parts of the event"
    - "&l/eog treasures &r-> opens the treasure manager"
    - "&l/eog shop ... &r-> manages the shop part"
    - " "
    - "&e&l! &eThe shop commands work if you the internal economy is enabled"
    - " "
    - "&c&l---------------------------------------------------------"